CREATE TABLE cake
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    calories           DECIMAL,
    image              VARCHAR(255),
    price              DECIMAL,
    weight             DECIMAL,
    compositions       VARCHAR(255),
    storage_conditions VARCHAR(255),
    CONSTRAINT pk_cake PRIMARY KEY (id)
);

CREATE TABLE userinf
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number VARCHAR(255)                            NOT NULL,
    name   VARCHAR(255),
    CONSTRAINT pk_userinf PRIMARY KEY (id)
);

ALTER TABLE userinf
    ADD CONSTRAINT uc_userinf_number UNIQUE (number);

CREATE TABLE orderinf
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    delivery         INTEGER,
    status           INTEGER,
    payment          INTEGER,
    delivery_address VARCHAR(255),
    delivery_time    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_orderinf PRIMARY KEY (id)
);

ALTER TABLE orderinf
    ADD CONSTRAINT FK_ORDERINF_ON_USER FOREIGN KEY (user_id) REFERENCES userinf (id);

CREATE TABLE purchase
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cake_id  BIGINT                                  NOT NULL,
    order_id BIGINT                                  NOT NULL,
    number   INTEGER,
    CONSTRAINT pk_purchase PRIMARY KEY (id)
);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_CAKE FOREIGN KEY (cake_id) REFERENCES cake (id);

ALTER TABLE purchase
    ADD CONSTRAINT FK_PURCHASE_ON_ORDER FOREIGN KEY (order_id) REFERENCES orderinf (id);

